### ISSUE TITLE
Codox doesn't see protocol functions imported by Potemkin

### ISSUE THREAD

**Issue by Engelberg** [ztellman/potemkin#25]
I don't really know whether this is a codox issue or a potemkin issue.  I'm raising it as an issue here, because my best guess is that the underlying issue is that something about the metadata attached to potemkin-imported protocol functions isn't quite right, so codox doesn't recognize it.

**Comment by Engelberg** [comment]
Last July, I emailed you an example of vars imported via potemkin that aren't showing up in codox.  Did you ever get a chance to look at that?  Thanks.

**Comment by xsc** [comment]
> [...] my best guess is that the underlying issue is that something about the metadata attached to potemkin-imported protocol functions isn't quite right. [...]

Actually, it's completely right. Codox has this feature where it groups protocol functions together with the corresponding protocol - but if the protocol cannot be found in the same namespace those functions just disappear.

So, IMO, it is not a potemkin issue (and I opened a PR that might fix the issue at codox).
