### ISSUE TITLE
wow, awesome naming!

### ISSUE THREAD

**Issue by ar7n** [ztellman/potemkin#58]

**Comment by ztellman** [comment]
thank you

**Comment by razum2um** [comment]
@ztellman I know what you've done for community and highly respect you, thanks for this lib as well.

But still there's an issue imo: e.g. I discovered this only *after I followed you* (long ago, maybe before github introduced pinned repos and I 👍 you pinned this) and *digged into aleph source*

Although both reexport vars and act-like-a-map approaches are very *essential* for idiomatic interfaces, they're hardly searchable: 

https://duckduckgo.com/?q=like+a+Clojure+map&t=h_&ia=web 
https://www.google.com/search?q=like+a+Clojure+map&ie=utf-8&oe=utf-8&aq=t

https://duckduckgo.com/?q=clojure+implement+map+protocols&t=h_&ia=web 
https://www.google.com/search?q=clojure+implement+map+protocols

https://duckduckgo.com/?q=clojure+reexport+vars&t=h_&ia=web 
^ missing potemkin everywhere

https://www.google.com/search?q=clojure+reexport+vars
^ al last only the 3rd link for me

Don't get this too serious, I'm ok if you don't care 😀

I also understand the backstory "expose smth/be like a" => "painted facade / to mimic real" => "Potemkin village" and ❤this as well.

**Comment by razum2um** [comment]
sorry for bumping this again, just found another spectacular example of non-googlable naming: https://github.com/wtetzner/exploding-fish and see https://github.com/lambdaisland/uri#similar-projects

> I was not aware at the time of creating lambdaisland/uri of exploding fish
